#!/usr/bin/env python3
"""Sync shared core files into both mod worktrees.

Usage (from the core repo root):
  python tools/sync_core.py [--check]

Copies every tracked core file under common/, docs/gdd shared systems,
.scratch/scripts/extract_sandbox.py, AGENTS.md, docs/agents/,
prepare-release.ps1 and .gitattributes into:
  _sandbox and _sandbox-r56 (paths resolved via MODS_ROOT env or the
  default Paradox mod folder layout on this machine).

--check only reports drifts without copying.

Core-owned paths inside each mod (authoritative copy lives here):
  common/**/*.hsl + common/macros.hml EXCEPT the per-mod catalogs:
    common/scripted_effects/99_sandbox_scenarios.hsl
    common/scripted_triggers/99_sandbox_scenario_triggers.hsl
    common/game_rules/99_sandbox_scenario_rules.hsl
    common/on_actions/99_sandbox_on_actions.hsl   (generated from the core
      skeleton + per-mod arc hooks; do not edit by hand)
    common/scripted_effects/99_sandbox_arc_hooks.hsl (generated by
      tools/extract_arc_hooks.py from the mod's scenario catalog)

The per-mod catalogs also hold the mod-specific hooks the shared core calls
but cannot define itself, because they reference per-mod content ids:
  sandbox_delay_capped_cw_missions_mod() (called from the core weekly
    mission-delay loop; the core keeps only vanilla mission ids)
  sandbox_afg_bop_cw_fuse_ready / sandbox_retry_afg_bop_civil_war_fuse
    (Rt56-only AFG BoP; the trigger lives in the trigger catalog)
"""
from __future__ import annotations

import hashlib
import os
import sys
from pathlib import Path

CORE = Path(__file__).resolve().parents[1]
DEFAULT_MODS = Path.home() / "Documents/Paradox Interactive/Hearts of Iron IV/mod"
MODS = Path(os.environ.get("MODS_ROOT", str(DEFAULT_MODS)))
TARGETS = [MODS / "_sandbox", MODS / "_sandbox-r56"]

# Shared GDD systems. Only National Focuses.md is byte-identical between mods;
# Honor/Civil Wars/Tyranny/Rivals GDDs drift per mod (r56 acceptance checklists
# are unchecked, plus an r56-only scenario-exemption line) and stay per-mod.
SHARED_GDD = [
    "docs/gdd/National Focuses.md",
]

# Core skeleton reference: lives in core only, never copied (each mod holds a
# generated 99_sandbox_on_actions.hsl built from this skeleton + arc hooks).
EXPECTED_ONLY_CORE = {
    "common/on_actions/99_sandbox_core_on_actions.hsl",
}

SHARED_MISC = [
    ".scratch/scripts/extract_sandbox.py",
    "AGENTS.md",
    "docs/agents/domain.md",
    "docs/agents/issue-tracker.md",
    "docs/agents/triage-labels.md",
    "prepare-release.ps1",
    ".gitattributes",
]

# Per-mod catalogs: never overwritten by the sync.
EXCLUDE = {
    "common/scripted_effects/99_sandbox_scenarios.hsl",
    "common/scripted_triggers/99_sandbox_scenario_triggers.hsl",
    "common/game_rules/99_sandbox_scenario_rules.hsl",
    "common/on_actions/99_sandbox_on_actions.hsl",
    "common/scripted_effects/99_sandbox_arc_hooks.hsl",
}


def core_files() -> list[Path]:
    out: list[Path] = []
    for p in sorted((CORE / "common").rglob("*")):
        if p.is_file() and p.suffix in (".hsl", ".hml"):
            rel = p.relative_to(CORE).as_posix()
            if rel not in EXCLUDE:
                out.append(p)
    for rel in SHARED_GDD + SHARED_MISC:
        p = CORE / rel
        if p.exists():
            out.append(p)
    return out


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()[:12]


def main() -> None:
    check = "--check" in sys.argv
    files = core_files()
    print(f"core files: {len(files)}")
    errors = 0
    for target in TARGETS:
        if not target.exists():
            print(f"SKIP missing mod dir: {target}")
            continue
        synced = 0
        drifted: list[str] = []
        for src in files:
            rel = src.relative_to(CORE)
            dst = target / rel
            if not dst.exists():
                if rel.as_posix() in EXPECTED_ONLY_CORE:
                    continue
                drifted.append(f"ONLY-CORE {rel.as_posix()}")
                continue
            if sha(src) != sha(dst):
                drifted.append(f"DIFF {rel.as_posix()}")
                if not check:
                    dst.parent.mkdir(parents=True, exist_ok=True)
                    dst.write_bytes(src.read_bytes())
                    synced += 1
        print(f"{target.name}: drifted={len(drifted)}" + (f" synced={synced}" if not check else ""))
        for d in drifted:
            print(f"  {d}")
        errors += len(drifted) if check else 0
    sys.exit(1 if check and errors else 0)


if __name__ == "__main__":
    main()
